Casadm error message update
Open-CAS/open-cas-linux pull request #1074
Opened 2022-02-25 16:14 UTC by kmajzero

Error message updated for the case of not meeting the space requirements
for the cache device.

Signed-off-by: Krzysztof Majzerowicz-Jaszcz <krzysztof.majzerowicz-jaszcz@intel.com>

2022-02-28 13:19 UTC, jfckm requested changes

2022-02-28 13:19 UTC, jfckm commented on casadm/extended_err_msg.c
> +		"Device does not meet requirements. Check kernel dmesg for details"
It would be good if we used same wording in both `KCAS_ERR_DETACHED` and here - they both direct users to check dmesg.

2022-03-03 08:55 UTC, jfckm approved these changes

2022-03-03 08:59 UTC, robertbaldyga approved these changes

2022-03-03 09:01 UTC, merged