casadm standby cache commands for tests
Open-CAS/open-cas-linux pull request #1075
Opened 2022-02-28 14:15 UTC by pdebski21

New casadm commands for standby mode and change of naming convention following new design.

2022-02-28 16:01 UTC, Deixx requested changes

2022-02-28 16:03 UTC, Deixx requested changes
Don't include OCF in PRs which should not touch OCF

2022-03-01 13:35 UTC, pep8speaks commented
Hello @pdebski21! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`test/functional/api/cas/casadm.py`](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py):

> [Line 58:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L58): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 59:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L59): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 59:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L59): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 59:6](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L59): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 60:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L60): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 60:5](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L60): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 60:6](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L60): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 61:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L61): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 62:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L62): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 63:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L63): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 64:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L64): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 64:4](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L64): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 64:53](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L64): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 65:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L65): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 66:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L66): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 67:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L67): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 68:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L68): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 68:9](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L68): [E112](https://duckduckgo.com/?q=pep8%20E112) expected an indented block
> [Line 69:5](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/casadm.py#L69): [E901](https://duckduckgo.com/?q=pep8%20E901) IndentationError: unindent does not match any outer indentation level

* In the file [`test/functional/api/cas/cli.py`](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/cli.py):

> [Line 94:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/cli.py#L94): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 94:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/cli.py#L94): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 94:5](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/cli.py#L94): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 95:1](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/cli.py#L95): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 95:32](https://github.com/Open-CAS/open-cas-linux/blob/3418cc8ee9ebc6cbbe2bd2fc6792e0d0371e4975/test/functional/api/cas/cli.py#L95): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2022-03-04 09:52 UTC, Deixx requested changes

2022-03-04 09:52 UTC, Deixx commented on test/functional/api/cas/casadm.py
> +        reload_kernel_module("cas_cache", kernel_params.get_parameter_dictionary())
drop reloading kernel modules when loading cache (we don't want to change the settings when we're restoring the cache)

2022-03-04 09:52 UTC, Deixx commented on test/functional/api/cas/cli.py
> +    command = " --standby --init "
cosmetic: remove the space after `--init` (all the params below have a preceding space)

2022-03-04 09:52 UTC, Deixx commented on test/functional/api/cas/cli.py
> +    if cache_id is not None:
remove the condition (cache id is mandatory)

2022-03-04 09:52 UTC, Deixx commented on test/functional/api/cas/cli.py
> +    if cache_line_size is not None:
remove the condition (cache line size is mandatory)

2022-03-04 09:52 UTC, Deixx commented on test/functional/api/cas/cli.py
> +
add `return casadm_bin + command`

2022-03-04 09:52 UTC, Deixx commented on test/functional/api/cas/cli.py
> +    command = " --standby --load "
cosmetic: remove the space after `--load`

2022-03-04 09:52 UTC, Deixx commented on test/functional/api/cas/cli.py
> +    command = " --standby --detach "
cosmetic: remove the space after `--detach`

2022-03-04 09:52 UTC, Deixx commented on test/functional/api/cas/cli.py
> +    command = " --standby --activate "
cosmetic: remove the space after `--activate`

2022-03-04 10:50 UTC, Deixx requested changes

2022-03-04 10:50 UTC, Deixx commented on test/functional/api/cas/casadm.py
> +                 kernel_params: KernelParameters = KernelParameters()):
remove kernel_params from args also ;)

2022-03-04 11:12 UTC, Deixx approved these changes

2022-03-07 08:14 UTC, robertbaldyga approved these changes

2022-03-08 07:26 UTC, merged