Don't allow flush/purge while cache is in standby
Open-CAS/open-cas-linux pull request #1127
Opened 2022-03-23 13:55 UTC by jfckm

Fixes #1117 

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-cas/open-cas-linux/1127)

2022-03-23 14:40 UTC, robertbaldyga requested changes

2022-03-23 14:40 UTC, robertbaldyga commented on modules/cas_cache/layer_cache_management.c
> +	if (ocf_cache_is_standby(cache)) {
Don't we want to handle this in OCF? IMO this check doesn't belong to the adapter layer.

2022-03-23 14:40 UTC, robertbaldyga commented on modules/cas_cache/layer_cache_management.c
> +	if (ocf_cache_is_standby(cache)) {
Ditto.

2022-03-24 08:44 UTC, jfckm commented
Obsolete. Fixed in https://github.com/Open-CAS/ocf/pull/678

2022-03-24 08:44 UTC, closed without merging