Fix for tests using get_metadata_size()
Open-CAS/open-cas-linux pull request #1269
Opened 2022-07-06 14:00 UTC by kmajzero

Since OCF has changed how metadata size is reported (OCF PR Open-CAS/ocf#744 ),
get_metadata_size() became get_metadata_size_on_device() and tests
using it are changed accordingly.

Signed-off-by: Krzysztof Majzerowicz-Jaszcz <krzysztof.majzerowicz-jaszcz@intel.com>

2022-07-06 15:26 UTC, robertbaldyga approved these changes

2022-07-06 19:19 UTC, robertbaldyga requested changes

2022-07-06 19:19 UTC, robertbaldyga commented on test/functional/api/cas/dmesg.py
> +    raise ValueError("Can't find the metadata size in the provided dmesg outputttt")
ttttoo many tttts

2022-07-07 07:37 UTC, kmajzero commented on test/functional/api/cas/dmesg.py
> +    raise ValueError("Can't find the metadata size in the provided dmesg outputttt")
ttttry to fix tttthat

2022-07-07 08:00 UTC, robertbaldyga approved these changes

2022-07-07 08:30 UTC, jfckm approved these changes

2022-07-07 10:32 UTC, merged