Startup test
Open-CAS/open-cas-linux pull request #1275
Opened 2022-07-12 11:43 UTC by mmichal10

2022-07-12 18:32 UTC, arutk commented
retest this please

2022-07-12 20:46 UTC, arutk submitted a review, later dismissed

2022-07-13 06:27 UTC, pep8speaks commented
Hello @mmichal10! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`test/functional/tests/initialize/test_startup_init_config.py`](https://github.com/Open-CAS/open-cas-linux/blob/88ce06cb22a1f8ebf7863301dcd46271b43dc1b1/test/functional/tests/initialize/test_startup_init_config.py):

> [Line 200:17](https://github.com/Open-CAS/open-cas-linux/blob/88ce06cb22a1f8ebf7863301dcd46271b43dc1b1/test/functional/tests/initialize/test_startup_init_config.py#L200): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 202:13](https://github.com/Open-CAS/open-cas-linux/blob/88ce06cb22a1f8ebf7863301dcd46271b43dc1b1/test/functional/tests/initialize/test_startup_init_config.py#L202): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line

2022-07-13 07:34 UTC, jfckm requested changes

2022-07-13 07:34 UTC, jfckm commented on test/functional/tests/initialize/test_startup_init_config.py
> +        core_pool_paths = set([c["device"] for c in core_pool_list])
you can use set comprehension here - 
```python
{c["device"] for c in core_pool_list}
```

2022-07-13 07:34 UTC, jfckm commented on test/functional/tests/initialize/test_startup_init_config.py
> +        caches_list = get_cas_devices_dict()["caches"].items()
since you are using only values from this dictionary you can use `.values()` getter

2022-07-13 07:34 UTC, jfckm commented on test/functional/tests/initialize/test_startup_init_config.py
> +        cores_list = get_cas_devices_dict()["cores"].items()
same here

2022-07-13 07:34 UTC, jfckm commented on test/functional/tests/initialize/test_startup_init_config.py
> +        caches_paths = set([c["device"] for _, c in caches_list])
set comprehension will work here as well

2022-07-13 07:34 UTC, jfckm commented on test/functional/tests/initialize/test_startup_init_config.py
> +        cores_paths = set([c["device"] for _, c in cores_list])
ditto

2022-07-13 07:34 UTC, jfckm commented on test/functional/tests/initialize/test_startup_init_config.py
> +        cores_states = dict((c["device"], c["status"]) for _, c in cores_list)
here you could use dict comprehension
```python
{c["device"]: c["status"] for c in cores_list} # only c assuming you got .values() before, not .items()
```

2022-07-18 08:13 UTC, arutk approved these changes

2022-07-18 08:15 UTC, jfckm approved these changes

2022-07-18 08:23 UTC, merged