tests: add test for adding invalid cores devices to caches
Open-CAS/open-cas-linux pull request #1309
Opened 2022-08-16 10:12 UTC by DocentSzachista

Signed-off-by: Damian Raczkowski <damian.raczkowski@intel.com>

2022-08-16 10:12 UTC, pep8speaks commented
Hello @DocentSzachista! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`test/functional/tests/ci/test_basic.py`](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py):

> [Line 13:49](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L13): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 21:7](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L21): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 22:7](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L22): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 23:7](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L23): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 24:7](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L24): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 24:68](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L24): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 26:7](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L26): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 27:9](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L27): [E121](https://duckduckgo.com/?q=pep8%20E121) continuation line under-indented for hanging indent
> [Line 28:11](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L28): [E121](https://duckduckgo.com/?q=pep8%20E121) continuation line under-indented for hanging indent
> [Line 32:7](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L32): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 33:9](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L33): [E121](https://duckduckgo.com/?q=pep8%20E121) continuation line under-indented for hanging indent
> [Line 34:11](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L34): [E121](https://duckduckgo.com/?q=pep8%20E121) continuation line under-indented for hanging indent
> [Line 38:7](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L38): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 39:9](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L39): [E121](https://duckduckgo.com/?q=pep8%20E121) continuation line under-indented for hanging indent
> [Line 40:11](https://github.com/Open-CAS/open-cas-linux/blob/04df0bd45d7d1db96506e0c947b1ca1f249eb885/test/functional/tests/ci/test_basic.py#L40): [E121](https://duckduckgo.com/?q=pep8%20E121) continuation line under-indented for hanging indent

2022-08-16 12:13 UTC, pdebski21 commented on test/functional/tests/ci/test_basic.py
> +    with TestRun.step("Start cache with ID=1 on cache device"):
You do not need to specify that id on that step.

2022-08-17 11:17 UTC, jfckm approved these changes

2022-08-17 12:08 UTC, pdebski21 commented on test/functional/tests/ci/test_basic.py
> +        partition_2 = cache_dev.partitions[1]
We pretty often align to convention:
```
cache_dev = TestRun.disks["cache_1"]
cache_dev.create_partitions([Size(2000, Unit.MebiByte)])
cache_dev = cache_dev.partitions[0]
```
using shadowing variables. So cache_dev is most often name for cache device as partition. Consider in context of test maybe convention of `cache_dev_used` or `cache_dev_occupied` and `cache_dev_free`.

2022-08-17 12:08 UTC, pdebski21 commented on test/functional/tests/ci/test_basic.py
> +            cli.start_cmd(partition_2.path, cache_id="1", force=True)
Consider additional variables for `cache_id`

2022-08-17 12:38 UTC, jfckm commented
@CAS-Linux-Jenkins ok to test

2022-08-17 13:55 UTC, pdebski21 approved these changes
Looks fine. Good job (:

2022-08-18 07:15 UTC, jfckm approved these changes

2022-08-18 12:29 UTC, karolinavelkaja commented on test/functional/tests/ci/test_basic.py
> +@pytest.mark.require_disk("cache_1", DiskTypeSet([DiskType.nand, DiskType.optane]))
is this test for CI? If yes please add proper pytest mark. If not just answear and I will marge this PR:)

2022-08-18 13:32 UTC, karolinavelkaja commented on test/functional/tests/ci/test_basic.py
> +@pytest.mark.require_disk("cache_1", DiskTypeSet([DiskType.nand, DiskType.optane]))
If I've checked correctly, looks like this should be part of new CI scpe, so please add:
@pytest.mark.CI

2022-08-18 13:32 UTC, karolinavelkaja requested changes
If I've checked correctly, looks like this should be part of new CI scope, so please add:
@pytest.mark.CI

2022-08-19 08:06 UTC, DocentSzachista commented
@karolinavelkaja Added :)

2022-08-19 08:07 UTC, jfckm approved these changes

2022-08-19 08:08 UTC, pdebski21 approved these changes

2022-08-19 09:09 UTC, karolinavelkaja approved these changes

2022-08-19 09:55 UTC, merged