Tests marking clean up (os-dependend and skipped)
Open-CAS/open-cas-linux pull request #1320
Opened 2022-08-25 15:38 UTC by karolinavelkaja

Marking all os-dependent tests with proper mark: @pytest.mark.os_dependent.

Mark: @pytest.mark.os_dependent_standby_mode_specific - means that those tests should be run only for scopes/clients which are using standby mode functionality (because of their complexity).

Adding mark: @pytest.mark.skip(reason="kedr not supported") - for kedr tests.

2022-09-07 07:43 UTC, jfckm approved these changes

2022-09-21 05:38 UTC, robertbaldyga requested changes

2022-09-21 05:38 UTC, robertbaldyga commented on test/functional/tests/incremental_load/test_udev.py
> +# Copyright(c) 2020-2022 Intel Corporation
There should not be change in the date when there is no change in the code.

2022-09-21 09:31 UTC, karolinavelkaja commented
Conflict resolved. One comment resolved. Ready :D

2022-10-14 05:24 UTC, jfckm approved these changes

2022-10-17 15:28 UTC, arutk approved these changes

2022-10-17 15:29 UTC, merged