Refactor disk/exp_obj API
Open-CAS/open-cas-linux pull request #1352
Opened 2022-09-19 13:58 UTC by robertbaldyga

2022-09-21 14:46 UTC, robertbaldyga commented
retest this please

2022-09-23 12:02 UTC, arutk requested changes

2022-09-23 12:23 UTC, arutk approved these changes

2022-09-23 12:23 UTC, robertbaldyga commented on modules/cas_cache/exp_obj.c
> +	printk("cas_exp_obj_free %s\n", exp_obj->dev_name);
Done.

2022-09-26 07:28 UTC, mmichal10 approved these changes

2022-09-27 08:11 UTC, merged