Fix ALRU wake up time test and documentation
Open-CAS/open-cas-linux pull request #1353
Opened 2022-09-20 14:30 UTC by arutk

2022-09-21 05:33 UTC, robertbaldyga approved these changes

2022-09-26 10:22 UTC, arutk commented
retest this please

2022-09-27 07:08 UTC, mmichal10 approved these changes

2022-09-27 09:53 UTC, jfckm approved these changes

2022-09-27 20:24 UTC, robertbaldyga requested changes

2022-09-27 20:24 UTC, robertbaldyga commented on casadm/casadm.8
> +due to stalenes time and/or activity threshold constraints.
Aspell test fails on this: s/stalenes/staleness

2022-09-29 14:18 UTC, rafalste commented on test/functional/tests/lazy_writes/cleaning_policy/test_cleaning_params.py
> +                f"Expected minumum dirty data flushed: {data_to_flush}\n"
and a small typo

2022-09-30 08:21 UTC, arutk commented on test/functional/tests/lazy_writes/cleaning_policy/test_cleaning_params.py
> +                f"Expected minumum dirty data flushed: {data_to_flush}\n"
fixed

2022-09-30 08:25 UTC, robertbaldyga approved these changes

2022-09-30 09:04 UTC, merged