Kernel 6.0 support
Open-CAS/open-cas-linux pull request #1394
Opened 2022-10-26 17:08 UTC by kmajzero

This patch introduces kernel 6.0 support for Open CAS

Signed-off-by: Krzysztof Majzerowicz-Jaszcz <krzysztof.majzerowicz-jaszcz@intel.com>

2022-10-26 17:08 UTC, kmajzero commented
Tested, works on ArchLinux with kernel 6.0.2-arch1-1.

2022-10-27 18:33 UTC, robertbaldyga requested changes

2022-10-27 18:33 UTC, robertbaldyga commented on configure.d/1_has_discard_support.conf
> +		return bdev_max_discard_sectors(bd);
`return !!bdev_max_discard_sectors(bd);` would be more self-explaining.

2022-10-27 18:33 UTC, robertbaldyga commented on modules/cas_cache/volume/vol_block_dev_bottom.c
> +	if(!cas_has_discard_support(bd)) {
Missing space after `if`.

2022-10-28 08:56 UTC, robertbaldyga approved these changes

2022-11-03 10:31 UTC, KlaudiaJ approved these changes

2022-11-07 10:40 UTC, merged