Add write performance test
Open-CAS/open-cas-linux pull request #1499
Opened 2024-09-03 12:49 UTC by katlapinka

2024-09-03 12:49 UTC, pep8speaks commented
Hello @katlapinka! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`test/functional/tests/performance/test_performance_reads.py`](https://github.com/Open-CAS/open-cas-linux/blob/5eab4a547a221319231cc09beae52f8bada54739/test/functional/tests/performance/test_performance_reads.py):

> [Line 106:62](https://github.com/Open-CAS/open-cas-linux/blob/5eab4a547a221319231cc09beae52f8bada54739/test/functional/tests/performance/test_performance_reads.py#L106): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 106:66](https://github.com/Open-CAS/open-cas-linux/blob/5eab4a547a221319231cc09beae52f8bada54739/test/functional/tests/performance/test_performance_reads.py#L106): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator

* In the file [`test/functional/tests/performance/test_performance_write.py`](https://github.com/Open-CAS/open-cas-linux/blob/5eab4a547a221319231cc09beae52f8bada54739/test/functional/tests/performance/test_performance_write.py):

> [Line 103:70](https://github.com/Open-CAS/open-cas-linux/blob/5eab4a547a221319231cc09beae52f8bada54739/test/functional/tests/performance/test_performance_write.py#L103): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 103:74](https://github.com/Open-CAS/open-cas-linux/blob/5eab4a547a221319231cc09beae52f8bada54739/test/functional/tests/performance/test_performance_write.py#L103): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator

2024-09-03 13:50 UTC, Deixx approved these changes

2024-09-03 17:35 UTC, robertbaldyga requested changes

2024-09-03 17:35 UTC, robertbaldyga commented on test/functional/tests/performance/test_performance_write.py
> +    title: Test Open CAS performance for 100% write inserts scenario in write-back mode.
The title says it's write inserts test (which is consistent with the implementation), but the name says "write_hit_wb". I suggest to change the name to "write_insert_wb".

2024-09-04 06:40 UTC, Deixx approved these changes

2024-09-04 09:22 UTC, robertbaldyga submitted a review, later dismissed

2024-09-04 09:30 UTC, Deixx approved these changes

2024-09-04 09:32 UTC, robertbaldyga approved these changes

2024-09-04 09:32 UTC, merged