configure framework: detect make_req_fn type
Open-CAS/open-cas-linux pull request #1531
Opened 2024-09-25 06:16 UTC by mmichal10

2024-09-25 13:44 UTC, robertbaldyga requested changes

2024-09-25 13:44 UTC, robertbaldyga commented on configure.d/1_make_req_type.conf
> +            # to a variable we're assuming the function is of type void.
s/to a variable/to int/

2024-09-25 13:45 UTC, robertbaldyga requested changes

2024-09-25 13:45 UTC, robertbaldyga commented on configure.d/1_make_req_type.conf
> +            # If it's impossible to assign the casted return value of submit_bio()
s/assign the casted return value/cast the return value/

2024-09-25 14:25 UTC, robertbaldyga approved these changes

2024-10-01 13:35 UTC, rafalste approved these changes
Looks good except for inconsistent indentation (mixed 4 and 8 spaces). I've checked other configure.d files and there are even worse mixing of tabs and spaces, so you have at least only spaces in yours. ;)

2024-10-02 08:33 UTC, merged