Create 3 data integrity tests
Open-CAS/open-cas-linux pull request #465
Opened 2020-07-16 14:25 UTC by Ostrokrzew

Create 3 tests, long for 2 hours, to verify data integrity based on different
patterns. Tests uses FIO to write and verify patterns.
Create file with patterns for testing purposes.

2020-07-16 15:12 UTC, Deixx commented on test/functional/tests/data_integrity/pattern_utils.py
> +#
I think test-framework would be better location for patterns util

2020-07-16 15:21 UTC, Deixx commented on test/functional/tests/data_integrity/pattern_utils.py
> +class Patterns(Enum):
rename to Pattern

2020-07-16 15:22 UTC, Deixx commented on test/functional/tests/data_integrity/pattern_utils.py
> +    random_pattern = _get_random_pattern()
remove '_pattern' from names (so we can call Pattern.cyclic instead of Patterns.cyclic_pattern)

2020-07-16 15:23 UTC, Deixx commented on test/functional/tests/data_integrity/test_data_integrity_with_patterns.py
> +    with TestRun.step(f"start cache in {cache_mode} mode"):
Start with capital letter

2020-07-16 15:23 UTC, Deixx commented on test/functional/tests/data_integrity/test_data_integrity_with_patterns.py
> +          Run fio on each core with single pattern and verify if there's no write errors.
Run fio with single pattern on each core
there are

2020-07-16 15:24 UTC, Deixx commented on test/functional/tests/data_integrity/test_data_integrity_with_patterns.py
> +          Data integrity test with different write patterns with duration time 2 hours
with 2 hours duration time

2020-07-16 15:28 UTC, Deixx commented on test/functional/tests/data_integrity/test_data_integrity_with_patterns.py
> +        cache_dev.create_partitions([exp_obj_size * exp_obj_number])
reduce cache size, lets see some eviction ;)

2020-07-16 15:37 UTC, Deixx commented on test/functional/tests/data_integrity/test_data_integrity_with_patterns.py
> +        .set_param("do_verify", 0)
When you turn off verification, you're ridding the test of its core function - data integrity verification. In this test we don't focus on io errors but rather on verification errors.

2020-07-16 15:38 UTC, Deixx commented on test/functional/tests/data_integrity/test_data_integrity_with_patterns.py
> +        .continue_on_error(ErrorFilter.io)
You can replace the filter here with ErrorFilter.verify

2020-07-16 15:45 UTC, Deixx commented on test/functional/tests/data_integrity/test_data_integrity_with_patterns.py
> +        core_dev.create_partitions([exp_obj_size] * exp_obj_number)
increase number of cores to include all patterns (1 core per pattern)

2020-07-16 15:46 UTC, Deixx commented on test/functional/tests/data_integrity/test_data_integrity_with_patterns.py
> +            .set_param("do_verify", 0)
same here

2020-07-16 15:50 UTC, Deixx commented on test/functional/tests/data_integrity/test_data_integrity_with_patterns.py
> +        cache.stop()
I'm quite sure test cleanup takes care of that

2020-07-16 15:51 UTC, Deixx commented on test/functional/tests/data_integrity/test_data_integrity_with_patterns.py
> +def test_data_integrity_hi_lo_pattern(cache_mode):
all comments from above test

2020-07-16 15:51 UTC, Deixx commented on test/functional/tests/data_integrity/test_data_integrity_with_patterns.py
> +def test_data_integrity_mixed_patterns(cache_mode):
all comments from the first test

2020-07-17 13:10 UTC, pep8speaks commented
Hello @Ostrokrzew! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`test/functional/tests/data_integrity/test_data_integrity_with_patterns.py`](https://github.com/Open-CAS/open-cas-linux/blob/49c6b9dfad7c1369ce82e39ab2c6588ceebf6406/test/functional/tests/data_integrity/test_data_integrity_with_patterns.py):

> [Line 45:72](https://github.com/Open-CAS/open-cas-linux/blob/49c6b9dfad7c1369ce82e39ab2c6588ceebf6406/test/functional/tests/data_integrity/test_data_integrity_with_patterns.py#L45): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 101:72](https://github.com/Open-CAS/open-cas-linux/blob/49c6b9dfad7c1369ce82e39ab2c6588ceebf6406/test/functional/tests/data_integrity/test_data_integrity_with_patterns.py#L101): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 163:80](https://github.com/Open-CAS/open-cas-linux/blob/49c6b9dfad7c1369ce82e39ab2c6588ceebf6406/test/functional/tests/data_integrity/test_data_integrity_with_patterns.py#L163): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 245:1](https://github.com/Open-CAS/open-cas-linux/blob/49c6b9dfad7c1369ce82e39ab2c6588ceebf6406/test/functional/tests/data_integrity/test_data_integrity_with_patterns.py#L245): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2020-07-21 08:46 UTC, imjfckm commented on test/functional/tests/data_integrity/test_data_integrity_with_patterns.py
> +        fio_errors = fio.get_results(fio_output.stdout)[0].total_errors()
`fio.run()` already returns `FioResult`, so you don't need to pull in this file and instantiate `FioResult` manually

2020-08-05 11:14 UTC, katlapinka commented on test/functional/tests/data_integrity/test_data_integrity_with_patterns.py
> +        cache_dev.create_partitions([exp_obj_size * (exp_obj_number * 1 / 4)])
is '* 1' really needed? ;) - the same in other tests

2020-08-31 07:22 UTC, katlapinka requested changes
Please resolve conflicts

2020-10-20 12:22 UTC, katlapinka approved these changes

2021-01-25 06:35 UTC, katlapinka commented
We decided to abandon those tests.

2021-01-25 06:35 UTC, closed without merging