Add trim test using devices supporting and not supporting discards
Open-CAS/open-cas-linux pull request #475
Opened 2020-07-23 14:59 UTC by katlapinka

Signed-off-by: Katarzyna Lapinska <katarzyna.lapinska@intel.com>

2020-07-23 14:59 UTC, pep8speaks commented
Hello @katlapinka! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`test/functional/tests/io/trim/test_trim.py`](https://github.com/Open-CAS/open-cas-linux/blob/7865bb93cd3ea3e70db35f99ffae73989030d96f/test/functional/tests/io/trim/test_trim.py):

> [Line 93:101](https://github.com/Open-CAS/open-cas-linux/blob/7865bb93cd3ea3e70db35f99ffae73989030d96f/test/functional/tests/io/trim/test_trim.py#L93): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 100 characters)

2020-07-24 10:56 UTC, katlapinka commented
Need redesign

2020-09-16 07:50 UTC, Ostrokrzew requested changes

2020-09-16 07:50 UTC, Ostrokrzew commented on test/functional/tests/io/trim/test_trim.py
> +        cache = casadm.start_cache(cache_dev, cache_mode)
Add force parameter, please.

2020-09-16 07:50 UTC, Ostrokrzew commented on test/functional/tests/io/trim/test_trim.py
> +                                              {"cache": True, "core": True}])
At this moment this cannot be dict (see: https://github.com/Open-CAS/test-framework/issues/210). For now You should change it to some immutable structure, e.g. tuple. And don't forget to update usage of `discard_support` according to changes.

2020-09-18 11:14 UTC, Ostrokrzew requested changes

2020-09-18 11:14 UTC, Ostrokrzew commented on test/functional/tests/io/trim/test_trim.py
> +    os_utils.drop_caches()
Please, add 1-2 seconds of sleep after `drop_caches()` - some DUTs, especially with RAIDs, need it.

2020-10-07 14:02 UTC, Ostrokrzew approved these changes

2020-10-20 13:25 UTC, Deixx submitted a review, later dismissed

2020-10-21 07:37 UTC, Deixx approved these changes

2020-10-21 10:57 UTC, robertbaldyga approved these changes

2020-10-21 10:57 UTC, merged