Test for loading cache from conf in different mode
Open-CAS/open-cas-linux pull request #526
Opened 2020-09-16 10:12 UTC by Ostrokrzew

Signed-off-by: Slawomir Jankowski <slawomir.jankowski@intel.com>

2020-09-16 10:12 UTC, pep8speaks commented
Hello @Ostrokrzew! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`test/functional/tests/initialize/test_startup_init_config.py`](https://github.com/Open-CAS/open-cas-linux/blob/b802ef0661069edacf01bdef4ccb98e9bde92146/test/functional/tests/initialize/test_startup_init_config.py):

> [Line 110:46](https://github.com/Open-CAS/open-cas-linux/blob/b802ef0661069edacf01bdef4ccb98e9bde92146/test/functional/tests/initialize/test_startup_init_config.py#L110): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 111:46](https://github.com/Open-CAS/open-cas-linux/blob/b802ef0661069edacf01bdef4ccb98e9bde92146/test/functional/tests/initialize/test_startup_init_config.py#L111): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 112:46](https://github.com/Open-CAS/open-cas-linux/blob/b802ef0661069edacf01bdef4ccb98e9bde92146/test/functional/tests/initialize/test_startup_init_config.py#L112): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 113:46](https://github.com/Open-CAS/open-cas-linux/blob/b802ef0661069edacf01bdef4ccb98e9bde92146/test/functional/tests/initialize/test_startup_init_config.py#L113): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

2020-09-30 12:47 UTC, katlapinka requested changes

2020-09-30 12:47 UTC, katlapinka commented on test/functional/tests/initialize/test_startup_init_config.py
> +            f"Cache did not load successfully - wrong number of caches: {caches_count}."
if len() method will raise exception due to none output of  casadm_parser.get_caches(), than caches_count will be not defined and will raise exception in this line.
I suggest executing casadm_parser.get_caches() in the begining of this method and use only it's output later to check if number of caches is OK and also to check if cache mode of returned cache is OK - then you can remove cache parameter from this method.

2020-09-30 12:47 UTC, katlapinka commented on test/functional/tests/initialize/test_startup_init_config.py
> +        TestRun.fail(f"Cache loaded with wrong number of cores: {cores_count}.")
same as in previous comment about not defined cores_count

2020-10-13 13:41 UTC, Deixx requested changes

2020-10-13 13:41 UTC, Deixx commented on test/functional/tests/initialize/test_startup_init_config.py
> +def test_cas_start_with_changed_mode(cache_mode_pair):
start => init

2020-10-13 13:41 UTC, Deixx commented on test/functional/tests/initialize/test_startup_init_config.py
> +      restart OpenCAS service and check if cache defined in config file starts properly.
all mentions of start => initialize, mention --force

2020-10-13 13:41 UTC, Deixx commented on test/functional/tests/initialize/test_startup_init_config.py
> +    with TestRun.step("Re-init and restart OpenCAS service."):
Reinitialize OpenCAS service with '--force' option.

2020-10-13 13:41 UTC, Deixx commented on test/functional/tests/initialize/test_startup_init_config.py
> +        casctl.start()
start() does nothing after init() (except for displaying errors that cache is already used)

2020-11-04 13:23 UTC, Deixx approved these changes

2020-11-05 08:25 UTC, Deixx approved these changes

2020-11-26 12:22 UTC, katlapinka approved these changes

2020-11-26 12:23 UTC, merged