Update CLI tests
Open-CAS/open-cas-linux pull request #532
Opened 2020-09-17 13:31 UTC by Ostrokrzew

2020-09-29 13:26 UTC, katlapinka requested changes

2020-09-29 13:26 UTC, katlapinka commented on test/functional/tests/cli/test_cli_start_stop.py
> +        title: Test for starting cache - short and long command version
This and previous test titles are the same. Please fix it.

2020-09-29 13:26 UTC, katlapinka commented on test/functional/tests/cli/test_cli_start_stop.py
> +            TestRun.fail("No core devices should be present after removing the core.")
core device

2020-09-29 13:26 UTC, katlapinka commented on test/functional/tests/cli/test_cli_start_stop.py
> +            TestRun.fail("No core devices should be present after removing the core.")
core device

2020-10-13 12:38 UTC, Deixx requested changes
Mostly grammar (I saw your grammar corrections and added mine), but not only ;)

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +            TestRun.fail(f"There is wrong number of caches found in the OS: {len(caches)}. "
a wrong number

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +            TestRun.fail(f"There is wrong number of caches found in the OS: {len(caches)}."
a wrong number

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +            TestRun.fail(f"There is wrong number of caches found in the OS: {len(caches)}. "
a wrong number

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +            TestRun.fail(f"The cache started using wrong device: {cache.cache_device.system_path}."
has started using a wrong device

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +            TestRun.fail(f"The cache started using wrong device: {cache.cache_device.system_path}."
has started using a wrong device

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +        cache_id = randint(1, 16384)
I'd either assign those numbers to some MIN/MAX_ALLOWED_ID variables or I'd add a comment, to clarify those numbers are not picked at random, but they are significant

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +            TestRun.fail(f"There is wrong number of caches found in the OS: {len(caches)}."
a wrong number

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +        title: Test for adding and removing core with default ID - short and long command version
a core with a default ID

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +          Start the new cache and add the core to it without passing core ID as an argument
a new cache and add a core ... a core ID

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +          - The core is added to the cache with default ID
a default ID

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +            TestRun.fail("One cache should be present still after removing the core.")
still present

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +        title: Test for adding and removing core with custom ID - short and long command version
a core with a custom ID

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +          Start the new cache and add the core to it with passing random core ID
a new cache ... a core ... a random core ID

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +    with TestRun.step("Start the cache and add the core with random ID."):
a random ID

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +            TestRun.fail("The core path should equal to the path of the core added.")
be equal

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +            TestRun.fail("One cache should be present still after removing the core.")
still present

2020-10-13 12:38 UTC, Deixx commented on test/functional/tests/cli/test_cli_start_stop.py
> +        core_id = randint(0, 4095)
Same as with cache id ranges

2020-11-04 13:05 UTC, Deixx approved these changes

2020-11-26 15:22 UTC, karolinavelkaja approved these changes

2020-11-27 07:47 UTC, katlapinka approved these changes

2020-11-27 08:14 UTC, merged