Tests for by-id core path
Open-CAS/open-cas-linux pull request #539
Opened 2020-09-30 14:25 UTC by Ostrokrzew

2020-10-13 11:54 UTC, Deixx requested changes

2020-10-13 11:54 UTC, Deixx commented on test/functional/tests/cache_ops/test_core_add.py
> +    with TestRun.step(f"Find symlinks in {by_id_dir} to {core_dev_link}."):
to ... in ...

2020-10-13 11:54 UTC, Deixx commented on test/functional/tests/initialize/test_startup_init_config.py
> +        core_dev_link = Symlink(core_dev.system_path).get_target()
same as in test_add_core_path_by_id

2020-10-13 11:54 UTC, Deixx commented on test/functional/tests/initialize/test_startup_init_config.py
> +                )
Seems unnecessary - basically checks if we read what we wrote

2020-10-13 11:54 UTC, Deixx commented on test/functional/api/cas/init_config.py
> +    def load_config_file(cls):
Considering comment for test_startup_init_config.py lines 174+, this method might be unnecessary

2020-12-18 11:03 UTC, katlapinka requested changes

2021-01-12 08:50 UTC, pep8speaks commented
Hello @Ostrokrzew! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`test/functional/tests/cache_ops/test_core_add.py`](https://github.com/Open-CAS/open-cas-linux/blob/9c1353307cbf1e47334913e8ff14be3d351edc85/test/functional/tests/cache_ops/test_core_add.py):

> [Line 194:32](https://github.com/Open-CAS/open-cas-linux/blob/9c1353307cbf1e47334913e8ff14be3d351edc85/test/functional/tests/cache_ops/test_core_add.py#L194): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 195:22](https://github.com/Open-CAS/open-cas-linux/blob/9c1353307cbf1e47334913e8ff14be3d351edc85/test/functional/tests/cache_ops/test_core_add.py#L195): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator

2021-08-20 13:34 UTC, karolinavelkaja commented
Closing since Sławek is no longer in our team and this PR needed few changes. 
New review: https://github.com/Open-CAS/open-cas-linux/pull/931

2021-08-20 13:34 UTC, closed without merging