Include headers needed for nvme structures
Open-CAS/open-cas-linux pull request #559
Opened 2020-10-29 18:27 UTC by anatol

It fixes following compilation issue:

  modules/cas_cache/utils/utils_nvme.c: In function ‘cas_nvme_get_nsid’:
  modules/cas_cache/utils/utils_nvme.c:27:28: error: ‘NVME_IOCTL_ID’ undeclared (first use in this function)
     27 |  ret = ioctl_by_bdev(bdev, NVME_IOCTL_ID, (unsigned long)NULL);
        |                            ^~~~~~~~~~~~~
  modules/cas_cache/utils/utils_nvme.c:27:28: note: each undeclared identifier is reported only once for each function it appears in
  modules/cas_cache/utils/utils_nvme.c: In function ‘cas_nvme_identify_ns’:
  modules/cas_cache/utils/utils_nvme.c:41:9: error: variable ‘cmd’ has initializer but incomplete type
     41 |  struct nvme_admin_cmd cmd = { };

2020-11-02 10:19 UTC, Ostrokrzew commented
ok to test

2020-11-03 16:06 UTC, arutk requested changes

2020-11-03 16:06 UTC, arutk commented on modules/cas_cache/utils/utils_nvme.c
> +#include <linux/nvme_ioctl.h>
Looks like this header is not present in older kernels (e.g. 3.19).  We typically handle differences between kernels using the ./configure script. You might want to consider adding a config option (e.g. HAS_NVME_IOCTL_H) which would expand to 1 if nvme_ioctl.h is present and include the file here conditionally, based on #if HAS_NVME_IOCTL_H.

2020-11-05 10:46 UTC, Deixx commented
@CAS-Linux-Jenkins ok to test

2020-11-05 11:29 UTC, Deixx commented
@anatol, please add Signed-off-by: Name <email> to your commit, so our Jenkins will let you pass ;)

2021-09-10 21:36 UTC, robertbaldyga commented
This patch is no longer needed, as problem got solved in other way.

2021-09-10 21:36 UTC, closed without merging