adding new test 'test_fault_power_hit_init'
Open-CAS/open-cas-linux pull request #578
Opened 2020-11-19 15:14 UTC by karolinavelkaja

Signed-off-by: Karolina Rogowska <karolina.rogowsky@gmail.com>

2020-11-24 15:40 UTC, mmichal10 commented on test/functional/tests/fault_injection/test_fault_power_hit_init.py
> +wait_time_15_s = 15
Unused variables

2020-11-25 16:37 UTC, Ostrokrzew requested changes

2020-11-25 16:37 UTC, Ostrokrzew commented on test/functional/tests/fault_injection/test_fault_power_hit_init.py
> +        title: Test with  power hit.
You did what I sometimes do - You didn't modify title.

2020-11-25 16:37 UTC, Ostrokrzew commented on test/functional/tests/fault_injection/test_fault_power_hit_init.py
> +        casadm.remove_all_detached_cores()
Is it needed? You didn't create config anywhere so cache wouldn't load at the system's start and there should be no unattached cores.

2020-11-30 14:06 UTC, karolinavelkaja commented on test/functional/tests/fault_injection/test_fault_power_hit_init.py
> +wait_time_15_s = 15
good catch, thanks!

2020-11-30 15:16 UTC, Ostrokrzew submitted a review, later dismissed

2020-12-15 14:35 UTC, katlapinka requested changes

2020-12-15 14:35 UTC, katlapinka commented on test/functional/tests/fault_injection/test_fault_power_hit_init.py
> +        power_control = TestRun.plugin_manager.get_plugin('power_control')
you have to add @pytest.mark with required power control plugin

2020-12-16 19:22 UTC, Ostrokrzew approved these changes

2020-12-21 12:56 UTC, katlapinka approved these changes

2020-12-21 12:57 UTC, merged