adding test 'test_fault_injection_raid_as_cache'
Open-CAS/open-cas-linux pull request #580
Opened 2020-11-25 15:12 UTC by karolinavelkaja

Signed-off-by: Karolina Rogowska <karolina.rogowsky@gmail.com>

2020-11-26 11:02 UTC, Ostrokrzew requested changes

2020-11-26 11:02 UTC, Ostrokrzew commented on test/functional/tests/fault_injection/test_fault_injection_raid_as_cache.py
> +        for i in range(0, 100):
I'd move `100` above the test and put it into variable like 'iterations' or something.

2020-11-27 14:22 UTC, katlapinka requested changes

2020-11-27 14:22 UTC, katlapinka commented on test/functional/tests/fault_injection/test_fault_injection_raid_as_cache.py
> +          Test if OpenCAS handle properly attempting of use CAS HDD member to build SW RAID.
I believe this is not a description for the below test ;)

2020-11-27 16:23 UTC, Ostrokrzew submitted a review, later dismissed

2020-12-21 13:04 UTC, katlapinka requested changes

2020-12-21 13:04 UTC, katlapinka commented on test/functional/tests/fault_injection/test_fault_injection_raid_as_cache.py
> +def test_fault_injection_raid_as_cache(cache_mode):
I think this test should not be placed in fault injection group. Please move it to the volumes test group and rename both file and test removing "fault_injection" part

2021-01-11 10:17 UTC, Ostrokrzew submitted a review, later dismissed

2021-01-21 11:07 UTC, katlapinka requested changes

2021-01-21 11:07 UTC, katlapinka commented on test/functional/tests/volumes/test_raid_as_cache.py
> +            size=Size(1, Unit.GiB))
I don't think size is needed here, especially that it's set to 1GiB and RAID is being built with two devices of size 2GiB

2021-01-21 11:07 UTC, katlapinka commented on test/functional/tests/volumes/test_raid_as_cache.py
> +        for i in range(0, files_number):
Please add removing created files at the end of this loop, because test cleanup will stop cache but will not remove files

2021-01-22 14:24 UTC, katlapinka approved these changes

2021-01-25 16:57 UTC, Ostrokrzew approved these changes

2021-03-06 19:00 UTC, merged