Adding test 'test_fault_injection_many_cores_raid_as_cache'
Open-CAS/open-cas-linux pull request #586
Opened 2020-12-01 17:28 UTC by karolinavelkaja

Signed-off-by: Karolina Rogowska <karolina.rogowsky@gmail.com>

2020-12-04 10:30 UTC, Ostrokrzew requested changes

2020-12-04 10:30 UTC, Ostrokrzew commented on test/functional/tests/fault_injection/test_fault_injection_many_cores_raid_as_cache.py
> +def compare_md5sums(md5_sums_source, files_cto_check_path):
'cto' in argument name
I assume it's typo, if not, sorry.

2020-12-04 10:30 UTC, Ostrokrzew commented on test/functional/tests/fault_injection/test_fault_injection_many_cores_raid_as_cache.py
> +    for i in range(0, md5_sums_elements):
This '0' isn't necessary.

2020-12-04 10:30 UTC, Ostrokrzew commented on test/functional/tests/fault_injection/test_fault_injection_many_cores_raid_as_cache.py
> +def create_files(destination_path, files_count):
I suggest You to rename this function, now it's not fully descriptive.

2020-12-15 09:03 UTC, Ostrokrzew submitted a review, later dismissed

2020-12-15 14:29 UTC, katlapinka requested changes

2020-12-15 14:29 UTC, katlapinka commented on test/functional/tests/fault_injection/test_fault_injection_many_cores_raid_as_cache.py
> +        cache = casadm.start_cache(raid_volume, cache_mode, force=True)
this line should be placed in the previous step

2020-12-15 14:29 UTC, katlapinka commented on test/functional/tests/fault_injection/test_fault_injection_many_cores_raid_as_cache.py
> +    with TestRun.step("Add core device to cache."):
"... , create filesystem and mount it"

2020-12-15 14:29 UTC, katlapinka commented on test/functional/tests/fault_injection/test_fault_injection_many_cores_raid_as_cache.py
> +    with TestRun.step("Add second core device to cache."):
"... , create filesystem and mount it"

2020-12-16 14:57 UTC, Ostrokrzew approved these changes

2020-12-21 13:11 UTC, katlapinka commented on test/functional/tests/fault_injection/test_fault_injection_many_cores_raid_as_cache.py
> +        title: Test if CAS is working with many cores devices using RAID0 as cache device.
"many core devices" - without "s" at the end of "cores"

2020-12-21 13:11 UTC, katlapinka commented on test/functional/tests/fault_injection/test_fault_injection_many_cores_raid_as_cache.py
> +          Test if CAS is working properly with many cores devices using RAID0 as cache device
here as well :)

2021-01-05 16:44 UTC, Ostrokrzew submitted a review, later dismissed

2021-01-25 07:24 UTC, katlapinka commented on test/functional/tests/volumes/test_many_cores_raid_as_cache.py
> +           and verification of data integrity of files copied to cores.
In my opinion  the first line of the description is sufficient :)

2021-01-25 07:24 UTC, katlapinka commented on test/functional/tests/volumes/test_many_cores_raid_as_cache.py
> +            size=Size(1, Unit.GiB))
Size unnecessary

2021-09-13 13:28 UTC, jfckm approved these changes

2021-09-13 20:19 UTC, robertbaldyga approved these changes

2021-09-13 20:20 UTC, merged