raid related fix for by-id path approach (ocl)
Open-CAS/open-cas-linux pull request #622
Opened 2021-01-08 15:49 UTC by karolinavelkaja

Signed-off-by: Karolina Rogowska <karolina.rogowska@intel.com>

2021-01-08 15:49 UTC, karolinavelkaja commented
Needs changes from: https://github.com/Open-CAS/test-framework/pull/228

2021-01-08 15:57 UTC, Ostrokrzew approved these changes

2021-01-20 12:00 UTC, katlapinka approved these changes

2021-01-27 18:50 UTC, Ostrokrzew requested changes
This path is out of date. Could be dropped.

2021-03-03 16:47 UTC, closed without merging