casadm robustness and security fixes
Open-CAS/open-cas-linux pull request #644
Opened 2021-01-20 15:37 UTC by arutk

2021-01-20 16:21 UTC, Ostrokrzew requested changes

2021-01-20 16:21 UTC, Ostrokrzew commented on casadm/cas_lib.c
> +		return failure;
FAILURE

2021-01-21 09:33 UTC, arutk commented on casadm/cas_lib.c
> +		return failure;
thanks

2021-01-21 10:23 UTC, robertbaldyga requested changes

2021-01-21 10:23 UTC, robertbaldyga commented on casadm/cas_lib.c
> +			}
Mixed tabs and spaces.

2021-01-21 12:10 UTC, arutk commented on casadm/cas_lib.c
> +			}
fixed

2021-01-21 12:13 UTC, robertbaldyga approved these changes

2021-01-21 12:17 UTC, mmichal10 approved these changes

2021-01-21 12:24 UTC, merged