doc: Requirements for cleaning
Open-CAS/open-cas-linux pull request #708
Opened 2021-02-24 10:59 UTC by mmichal10

Signed-off-by: Michal Mielewczyk <michal.mielewczyk@intel.com>

2021-02-26 10:00 UTC, Deixx requested changes

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +The product shall accept FLUSH_MAX_BUFFERS values in rage from 1 to 10000 inclusive.
```suggestion
The product shall accept FLUSH_MAX_BUFFERS values in range from 1 to 10000 inclusive.
```

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +---
In whole file 'set a as an active' -> 'set a as the active'

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +FLUSH_MAX_BUFFERS cache lines with frequency of WAKE_UP milliseconds.
'frequency' is a bit vague here - I'd suggest writing about intervals

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +When ACP is set as the active cleaning policy the product shall sort the cache lines
where are they sorted?

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +id: acp_flush_max_buffers_values
not consistent - in reqs for alru you did ...\_valid\_\<param\>

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +The value shall be interpreted as number of cache lines.
```suggestion
The value shall be interpreted as a number of cache lines.
```

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +The product shall accept FLUSH_MAX_BUFFERS in range from 1 to 10000 inclusive.
```suggestion
The product shall accept FLUSH_MAX_BUFFERS values in range from 1 to 10000 inclusive.
```

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +The product shall accept WAKE_UP in range from 0 to 10000 inclusive.
```suggestion
The product shall accept WAKE_UP values in range from 0 to 10000 inclusive.
```

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +one that had been used before the cache shut down.
can be simplified/shortened without losing the meaning.
```suggestion
When a cache state is loaded the product shall restore the cleaning policy used before the cache shut down.
```

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +values that had been set before the cache shut down.
```suggestion
When a cache state is loaded the product shall restore the ALRU parameters set before the cache shut down.
```

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +When a cache state is loaded the product shall restore parameters of ACP to the
same here

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +The product shall initialize ALRU with following parameters:
```suggestion
The product shall initialize ALRU with the following parameters:
```

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +The product shall initialize ACP with following parameters:
```suggestion
The product shall initialize ACP with the following parameters:
```

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +When initializing new cache instance the product shall set ALRU as a default
```suggestion
When initializing a new cache instance the product shall set ALRU as the default
```

2021-02-26 10:00 UTC, Deixx commented on doc/requirements/cleaning
> +The product shall allow to change cleaning policy in runtime.
parameters as well

2021-02-26 13:24 UTC, arutk requested changes

2021-03-03 10:36 UTC, Deixx requested changes

2021-03-03 10:36 UTC, Deixx commented on doc/requirements/cleaning
> +polices.
```suggestion
policies.
```

2021-03-03 10:36 UTC, Deixx commented on doc/requirements/cleaning
> +FLUSH_MAX_BUFFERS cache lines WAKE_UP milliseconds intervals.
```suggestion
FLUSH_MAX_BUFFERS cache lines in WAKE_UP milliseconds intervals.
```

2021-03-03 10:36 UTC, Deixx commented on doc/requirements/cleaning
> +When ALRU is  set as the active cleaning policy and the time passed since the last
```suggestion
When ALRU is set as the active cleaning policy and the time passed since the last
```

2021-03-03 10:36 UTC, Deixx commented on doc/requirements/cleaning
> +When ALRU is  set as the active cleaning policy the product shall flush dirty cache
```suggestion
When ALRU is set as the active cleaning policy the product shall flush dirty cache
```

2021-03-03 10:36 UTC, Deixx commented on doc/requirements/cleaning
> +When ALRU is  set as the active cleaning policy the product shall flush at most
```suggestion
When ALRU is set as the active cleaning policy the product shall flush at most
```

2021-03-03 10:36 UTC, Deixx commented on doc/requirements/cleaning
> +id: change_parmeters_in_runtime
```suggestion
id: change_parameters_in_runtime
```

2021-03-03 11:05 UTC, Deixx submitted a review, later dismissed

2021-03-03 12:05 UTC, arutk commented on doc/requirements/cleaning
> +The product shall accept ACTIVITY_THRESHOLD values in range from 0 to 1000000 inclusive.
I meant not to specify units in a separate requirement for the product. However for this requirement (and any other numeric values in this file) we have to state unit explicitly for it to be verifiable.

2021-03-11 10:13 UTC, arutk approved these changes

2021-04-21 11:09 UTC, Deixx approved these changes

2021-05-26 21:48 UTC, merged