add supporting methods for lvm tests in new file
Open-CAS/open-cas-linux pull request #723
Opened 2021-03-09 15:28 UTC by karolinavelkaja

Signed-off-by: Karolina Rogowska <karolina.rogowska@intel.com>

2021-03-10 09:54 UTC, Ostrokrzew approved these changes

2021-06-07 12:47 UTC, katlapinka commented on test/functional/tests/common/lvm_common_utils.py
> +    return cache, core
I think this is not a common method for lvm. It can be placed somewhere in the directory with tests, which use it

2021-06-07 12:47 UTC, katlapinka commented on test/functional/tests/common/lvm_common_utils.py
> +        .run())
same as above

2021-06-28 12:51 UTC, katlapinka approved these changes

2021-06-28 12:57 UTC, Ostrokrzew approved these changes

2021-08-05 07:25 UTC, Deixx requested changes

2021-08-05 07:25 UTC, Deixx commented on test/functional/tests/common/lvm_common_utils.py
> +opencas_conf_path = "/etc/opencas/opencas.conf"
use `from api.cas.init_config import opencas_conf_path` instead - keep the path in one place

2021-08-05 07:25 UTC, Deixx commented on test/functional/tests/common/lvm_common_utils.py
> +    config = fs_utils.read_file(opencas_conf_path)
`InitConfig.create_init_config_from_running_configuration()` returns the configuration - no need to read the file

2021-08-24 12:06 UTC, Deixx approved these changes

2021-09-06 13:04 UTC, rafalste approved these changes

2021-09-06 13:04 UTC, rafalste commented on test/functional/tests/common/lvm_common_utils.py
> +def run_fio_on_lvm(volumes: []):
If the `[]` meant to be a type hint, I believe `volumes: list` would be more pythonic. Just a suggestion.

2021-09-10 07:46 UTC, merged