test fix: test_attach_core_to_incomplete_cache_volume
Open-CAS/open-cas-linux pull request #776
Opened 2021-03-30 15:06 UTC by karolinavelkaja

Getting core device id before unplug for later validation of core inactive status

Signed-off-by: Karolina Rogowska <karolina.rogowska@intel.com>

2021-06-17 14:01 UTC, Deixx requested changes

2021-06-17 14:01 UTC, Deixx commented on test/functional/api/cas/core.py
>                      or split_line[5] == self.path):
I don't like mixing self.path and core_id provided as an argument in a single check. This method should be either connected to a specific core object or changed to a class/static method.

2021-08-31 05:15 UTC, Deixx requested changes
I don't get it. Are there changes in the actual test that should be included here?
Also, please take a look at https://github.com/Open-CAS/open-cas-linux/pull/936

2021-09-14 07:10 UTC, karolinavelkaja commented
Closing since changes with fix had been implemented and already merged - https://github.com/Open-CAS/open-cas-linux/pull/936

2021-09-14 07:10 UTC, closed without merging