update cli messages and tests accordingly
Open-CAS/open-cas-linux pull request #899
Opened 2021-07-28 12:57 UTC by karolinavelkaja

updated tests: test_recovery_unplug and test_fault_injection_with_mounted_core

Signed-off-by: Karolina Rogowska <karolina.rogowska@intel.com>

2021-08-05 06:37 UTC, Deixx requested changes

2021-08-05 06:37 UTC, Deixx commented on test/functional/tests/lazy_writes/recovery/test_recovery_unplug.py
> +            TestRun.LOGGER.warning("Expected stopping cache with errors.")
Try not to use api.cas.cli, if you don't necessarily need it.
`cache.stop(no_data_flush=True)` would suffice, and it throws a nice CmdException that contains output if exit_code is not 0.

2021-08-06 09:42 UTC, Deixx approved these changes

2021-08-09 09:21 UTC, mmichal10 approved these changes

2021-08-09 18:46 UTC, merged