Remove remains of atomic writes support
Open-CAS/open-cas-linux pull request #921
Opened 2021-08-12 15:18 UTC by mmichal10

Signed-off-by: Michal Mielewczyk <michal.mielewczyk@intel.com>

2021-08-16 03:57 UTC, robertbaldyga requested changes

2021-08-16 03:57 UTC, robertbaldyga commented on casadm/cas_lib.c
>  };
Do we still need this mapping? We have only one metadata mode right now.

2021-08-16 03:57 UTC, robertbaldyga commented on modules/cas_cache/volume/vol_blk_utils.c
> -	if (*type == BLOCK_DEVICE_VOLUME) {
Also `NVME_CONTROLLER` type does not seem to be used anywhere. And it should no longer be considered a valid type.

2021-08-16 14:14 UTC, robertbaldyga approved these changes

2021-08-17 13:11 UTC, rafalste approved these changes

2021-08-18 07:19 UTC, merged