adding tests for by-id core path
Open-CAS/open-cas-linux pull request #931
Opened 2021-08-20 13:33 UTC by karolinavelkaja

Original review: https://github.com/Open-CAS/open-cas-linux/pull/539 
Signed-off-by: Karolina Rogowska <karolina.rogowska@intel.com>

2022-03-02 12:18 UTC, arutk requested changes

2022-03-02 12:18 UTC, arutk commented on test/functional/tests/cache_ops/test_core_add.py
> +            paths_from_dmesg.append(get_added_core_path_from_dmesg())
there is no need to parse dmesg. "casadm -L -b" will print paths exactly as returned by OCF, without any translation.

2024-09-03 05:36 UTC, Deixx commented on test/functional/tests/initialize/test_startup_init_config.py
>  from test_utils.size import Unit, Size
could use some cleanup, like removing casadm_parser as a whole module from imports (all the needed functions from casadm_parser are imported) or importing casadm and from casadm

2024-09-03 05:37 UTC, Deixx reviewed
Adam's comments still relevant, but this should work almost "as is"

2024-09-12 13:46 UTC, katlapinka commented
Moved to https://github.com/Open-CAS/open-cas-linux/pull/1518

2024-09-12 13:46 UTC, closed without merging