cas api: add casadm commands for failover
Open-CAS/open-cas-linux pull request #975
Opened 2021-10-25 10:37 UTC by karolinavelkaja

Signed-off-by: Karolina Rogowska <karolina.rogowska@intel.com>

2021-11-02 14:01 UTC, Deixx requested changes

2021-11-02 14:01 UTC, Deixx commented on test/functional/api/cas/casadm.py
> +def detach_cache(cache_id: int, shortcut: bool = False):
Maybe you're right. But I'd leave at least `start_standby_cache` as is - it is after all a start-cache command with a flag.

2021-11-04 08:38 UTC, Deixx requested changes

2021-11-04 08:38 UTC, Deixx commented on test/functional/api/cas/casadm.py
> +        cache_dev=cache_dev.path, cache_line_size=cache_line_size, cache_id=cache_id,
we should pass strings as arguments to start_cmd, that is we have to "stringify" cache_line_size and cache_id

2021-11-04 08:38 UTC, Deixx commented on test/functional/api/cas/cli.py
> +    else:
Remove 'else' - methods in cli.py are meant to build a command the same way a user can (even with incorrect configuration) and in general they should not be called directly (excluding some cases like negative tests) but through casadm API which takes care of proper arguments being passed down.

2021-11-23 15:44 UTC, pdebski21 approved these changes

2022-02-03 16:52 UTC, karolinavelkaja commented
This PR needs to be updated to new design / function names when they will be present on master branch.

2022-02-28 15:37 UTC, pdebski21 commented
new design naming changes and review suggestions are present in new PR:
https://github.com/Open-CAS/open-cas-linux/pull/1075

2022-03-02 11:59 UTC, closed without merging