Shorten open-cas.service timeout
Open-CAS/open-cas-linux pull request #986
Opened 2021-11-09 19:14 UTC by robertbaldyga

As startup procedure got optimized recently, we can make timeout smaller.

Signed-off-by: Robert Baldyga <robert.baldyga@intel.com>

2021-11-09 20:13 UTC, mmichal10 submitted a review, later dismissed

2021-11-10 07:33 UTC, Deixx approved these changes

2021-11-10 08:03 UTC, arutk approved these changes

2021-11-10 08:08 UTC, arutk requested changes

2021-11-10 08:08 UTC, arutk commented on utils/open-cas.service
>  # Copyright(c) 2019-2021 Intel Corporation
Please update PR description as well (the one referring to shortening timeout)

2021-11-10 09:15 UTC, rafalste submitted a review, later dismissed

2021-11-10 10:27 UTC, robertbaldyga commented
retest this please

2021-11-10 10:44 UTC, Deixx approved these changes

2021-11-10 10:50 UTC, rafalste approved these changes

2021-11-10 10:54 UTC, merged